### PR TITLE
control-interface: [bindtodevice]

### PR DESCRIPTION
**Pull request by wtoorop**
As suggested by Andreas Schulze on nsd-users

### CODE REVIEW

**Comment by wtoorop** [comment]
TODO: update manpage and example nsd.conf

**Review by wcawijngaards — APPROVED** [review]
Looks okay to me, including portability to non-getifaddrs-supporting systems.

**Comment by wtoorop** [comment]
TODO2: Also adapt control-interface!

root@233ad0e3d5b6:/usr/local/etc/nsd# nsd-control status
could not parse IP: eth0

**Comment by andreasschulze** [comment]
just build master + branch features/control-interface-bindtodevice and can confirm, nsd-control works like expexted

**Comment by wtoorop** [comment]
@wcawijngaards In commit 6b15fbeb15 I just moved resolve_interface_names() (and the static auxiliary functions it calls) from nsd.c to options.c to resolve interface names of control interfaces too.
Do you want to re-review this? Or can I just merge?

**Comment by wcawijngaards** [comment]
It is fine from me!

**Pull request merged**
