### PR TITLE
Test package fixes

### PR DESCRIPTION
**Pull request by wtoorop**

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Maybe make this:
```
if test ! -f nsd.pid ; then
        exit 0
fi
if test -z `cat nsd.pid` ; then
```

A function in `common.sh`? Something like `kill_from_pidfile`?

**Comment by wtoorop** [comment]
@k0ekk0ek @wcawijngaards these are some non-intrusive fixes of the .tdir tests
Let me know if I can merge this...

**Review by k0ekk0ek — APPROVED** [review]
Nice addition :+1:

**Review by wcawijngaards — APPROVED** [review]
Lovely fixes, they all look good to have. The xfr_update fixes in particular as well the the new common.sh function that eases the test scripts.

**Comment by wtoorop** [comment]
Thanks @k0ekk0ek and @wcawijngaards ! Then I merge.

**Pull request merged**
