### PR TITLE
Catalog Zones

### PR DESCRIPTION
**Pull request by Koenvh1**
This PR implements catalog zone consumers as defined in [RFC 9432](https://datatracker.ietf.org/doc/html/rfc9432). This is a squash and rebase of #261 onto a recent version of the master branch to remove most of the noise caused by earlier implementation ideas without rewriting history on the previous branch.

EDIT (by @k0ekk0ek): `features/catalog-zones` is a feature branch that will collect the changes by @Koenvh1 (primary author) and @k0ekk0ek.

### CODE REVIEW

**Comment by pettai** [comment]
A noted behavior-change is that the catalog zone is never written to disk. Is that change from the previous branch intentional?

**Comment by k0ekk0ek** [comment]
@pettai, If a database is configured, the zone (on secondaries) is not written to disk. If no database is configured `database: ""` zones should be written to disk every 3600 seconds by default (configurable, see `zonefiles-write`). Note that the database option is set to be removed in the next release (#290). It could (of course) also be that there's a bug introduced by this PR. In the latter case, I'll happily dive into it, but please note that at this stage, the code is not quite ready for production testing. Reviews of #261 turned up some problems that @Koenvh1 and I are working to resolve. We're hoping to have something ready in a few weeks.

**Comment by pettai** [comment]
> @pettai, If a database is configured, the zone (on secondaries) is not written to disk. If no database is configured `database: ""` zones should be written to disk every 3600 seconds by default (configurable, see `zonefiles-write`). Note that the database option is set to be removed in the next release (#290). It could (of course) also be that there's a bug introduced by this PR. In the latter case, I'll happily dive into it, but please note that at this stage, the code is not quite ready for production testing. Reviews of #261 turned up some problems that @Koenvh1 and I are working to resolve. We're hoping to have something ready in a few weeks.

I just used `nsd-control write` before on the previous catz conf to write all zones in memory (after transfer) to disk. But after adding a explicit zonefile: statement to the catalog zone: itself, it is now written to disk 👍 
The new configuration option(s) follows nsd's generic behavior, so I rest my case 😄

**Comment by k0ekk0ek** [comment]
New implementation in #304. Closing this.

**Pull request closed without merging**
