### PR TITLE
Change zone parsing to accept non-trailing newline

### PR DESCRIPTION
**Pull request by TCY16**

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
So, basically what this change does is not make the zone parser require a newline to delimit the record. I'm ok with it. I don't particulary like the static variable, but the parser isn't thread-safe anyway, so I'd be fine with this getting merged. @wcawijngaards, @wtoorop, any comments?

**Comment by wcawijngaards** [comment]
I do not see any issues with it, if that works for non-newline-ended files, that is nice.

**Comment by k0ekk0ek** [comment]
@TCY16, can you update the changelog too? After that, I think we can go ahead and merge this.

**Comment by k0ekk0ek** [comment]
@TCY16, Changelog?

**Pull request merged**
